### ISSUE TITLE
Can there be functions to just compute a specific PK metric?

### ISSUE THREAD

**Issue by aelmokadem** [PharmCat/MetidaNCA.jl#2]
Hi,

Thank you so much for developing this useful package. I was wondering if there is a way to isolate the PK parameter functions! Like having something that would specifically measure auc or cmax etc.. rather than having to calculate all parameters with the `nca!` function then extracting those!

Thanks.

**Comment by PharmCat** [comment]
> Hi,

Hello! Thank you for the feedback!

First I should say that I thought about it, but rerally there is cause because it wasn't done.  Main purpose of packege - is to get appropriate parameters for many subject even is data not clear (missing values, NaN values, values before dosing ets), so that why NCA is computing for `PKSubject` structure witch conatain data about time, concentrations, dosing time ets. Also you can use settings for AUC calculation: use Linear Trapesoidal Rule, or Linear - Up, Log - Down, or Linear - Up, Log - Down only after Cmax, and you can define interpolation rule for missing data.

So there are steps:

1. `pkimport` step - make set of `PKSubject` from dataset, if data couldn't be parsed it replased by NaN
2. Compute NCA for set of subject (apply defined rules for AUC and interpolation) - make set of results
3. Get results or table


So if we want `auc` function it would likely this `auc(data, calcm = :lint, intpm = :lint)` , and it will need Tmax calculation too - and it will be not less complicated that `nca!`.

And if we want Cmax it is possible to make `cmax` function, but more robust to get Tmax and Cmax simultaniously.

Also we can use two approaches - make `auc` only for `PKSubject` or for two vectors - time and concentration. 

If you can provide more information about purpose or scenarios for isolated function - probably I can make that in next updates. (For example if it need for simulation I can maximize performace for some scenarios).

Also you can use `nca` function to get parameters directly from dataset without `pkimport` step. 

for example:

```
dsnca = nca(pkdata, :Time, :Concentration, [:Subject, :Formulation]; dosetime = DoseTime(dose = 100, time = 0))
dsnca[:, :AUClast]
```

If table need:

```
DataFrame(dsnca; results = [:AUClast, :Cmax])
```

**Comment by aelmokadem** [comment]
@PharmCat  thanks for your reply. What you said makes perfect sense. I was naively thinking that isolating these functions might lead to a less computational burden and a more efficient application if I don't need everything else that comes with `nca`! I am assessing the use of the package when running global sensitivity on PK params and AUC was one of these params so efficiency would be crucial here especially if I have a large number of samples.

**Comment by PharmCat** [comment]
> am assessing the use of the package when running global sensitivity on PK params and AUC was one of these params so efficiency would be crucial here especially if I have a large number of samples.

If you don't need `pkimport` step with sorting data to make subjects and have simulated data for each calculation as two vectors  (itime, concentration) it is possible to isolate AUC part (from AUMC and elimination parameters at least). It have sence to make simplified method to get AUC without missing, NaN and range checks in simulation purpose.

**Comment by aelmokadem** [comment]
@PharmCat  yeah it worked without `pkimport`.
